steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg STRIPE_SECRET_KEY=$$STRIPE_SECRET_KEY \
          --build-arg STRIPE_PUBLIC_KEY=$$STRIPE_PUBLIC_KEY \
          --build-arg RESEND_API_KEY=$$RESEND_API_KEY \
          --build-arg SUPABASE_URL=$$SUPABASE_URL \
          --build-arg SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY \
          --build-arg SUPABASE_SERVICE_ROLE_KEY=$$SUPABASE_SERVICE_ROLE_KEY \
          --build-arg STRIPE_WEBHOOK_SECRET=$$STRIPE_WEBHOOK_SECRET \
          -t us-central1-docker.pkg.dev/prairie-books/prairie-books/prairie-books:$COMMIT_SHA .
    secretEnv: ['STRIPE_SECRET_KEY', 'STRIPE_PUBLIC_KEY', 'RESEND_API_KEY', 'SUPABASE_URL', 'SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY', 'STRIPE_WEBHOOK_SECRET']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-central1-docker.pkg.dev/prairie-books/prairie-books:$COMMIT_SHA'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run','deploy', 'prairie-books --image us-central1-docker.pkg.dev/prairie-books/prairie-books:$COMMIT_SHA', '--region', 'us-central1']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_SECRET_KEY/versions/latest
      env: 'STRIPE_SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_PUBLIC_KEY/versions/latest
      env: 'STRIPE_PUBLIC_KEY'
    - versionName: projects/$PROJECT_ID/secrets/RESEND_API_KEY/versions/latest
      env: 'RESEND_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/SUPABASE_URL/versions/latest
      env: 'SUPABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/SUPABASE_ANON_KEY/versions/latest
      env: 'SUPABASE_ANON_KEY'
    - versionName: projects/$PROJECT_ID/secrets/SUPABASE_SERVICE_ROLE_KEY/versions/latest
      env: 'SUPABASE_SERVICE_ROLE_KEY'
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_WEBHOOK_SECRET/versions/latest
      env: 'STRIPE_WEBHOOK_SECRET'
options:
  logging: CLOUD_LOGGING_ONLY
