services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_STRIPE_API_KEY=${STRIPE_PUBLIC_KEY}
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: