name: GCP CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: prairie-books

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status

          export STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          export STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}
          export RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          export SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          export SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          export NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          export NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          export NEXT_PUBLIC_STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          export NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}
          export NEXT_PUBLIC_RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}


          docker build \
            --build-arg STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY" \
            --build-arg NEXT_PUBLIC_STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY" \
            --build-arg STRIPE_PUBLIC_KEY="$STRIPE_PUBLIC_KEY" \
            --build-arg NEXT_PUBLIC_STRIPE_PUBLIC_KEY="$STRIPE_PUBLIC_KEY" \
            --build-arg RESEND_API_KEY="$RESEND_API_KEY" \
            --build-arg NEXT_PUBLIC_RESEND_API_KEY="$RESEND_API_KEY" \
            --build-arg SUPABASE_URL="$SUPABASE_URL" \
            --build-arg NEXT_PUBLIC_SUPABASE_URL="$SUPABASE_URL" \
            --build-arg SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
            -t gcr.io/prairie-books/cloud-run-source-deploy/prairie-books/prairie-books:${{ github.sha }} \
            .

          docker push gcr.io/prairie-books/cloud-run-source-deploy/prairie-books/prairie-books:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: prairie-books
          image: gcr.io/prairie-books/cloud-run-source-deploy/prairie-books/prairie-books:${{ github.sha }}
          region: us-central1
          project_id: prairie-books
